services:
  my_postgres_db:
    image: postgres:16
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: gcorsaw
      POSTGRES_PASSWORD: DadR0cks
      POSTGRES_DB: mydatabase 
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: